version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686" # http://0.0.0.0:16686
    networks:
      - jaeger-example

networks:
  jaeger-example: