version: '3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - "3001:3001" # http://0.0.0.0:3001/dashboard
    volumes:
      - uptime-kuma:/app/data
    restart: always

volumes:
  uptime-kuma:
